name: flutter_application_2
description: A new Flutter project.

version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_calendar: ^20.1.57

  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.5
  flutter_native_splash: ^2.1.3+1

flutter_native_splash:
  color: "#add8e6"
  image: "assets/images/splash.png"
  color_dark: "#262626"
  image_dark: "assets/images/splash.png"
  fullscreen: true
  android_12:
    icon_background_color: "#add8e6"
    image: "assets/images/splash_android12.png"
    icon_background_color_dark: "#262626"
    image_dark: "assets/images/splash_android12.png"
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dev_dependencies:
  flutter_native_splash: ^2.1.3+1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "images/launcher_icon.png"

#  flutter_lints: ^1.0.0

#flutter:
#  uses-material-design: true

#  assets:
#    - images/
